spring.config.import=file:env.properties
spring.application.name=GithubUserActivity

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/github_users
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
